---
- hosts: localhost

  vars_files:
  - versions.yml

  # - .env_vars.yml
  # environment: "{{ env_vars }}"

  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - core
    when:
      - ansible_os_family == 'Debian'

  tasks:
    - name: Detect WSL
      become: true
      shell: grep -qi microsoft /proc/version && echo wsl || /bin/true
      register: detect_wsl_result
      tags:
        - full

    - name: Generate ssh keys
      import_tasks: ansible/ssh.yml

    - name: pipx - install global python binaries
      import_tasks: ansible/pipx-packages.yml
      tags:
        - pipx
