---
- name: neovim - install prerequisites with apt
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - doxygen

- name: neovim - checkout version
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/install/neovim"
    version: "48e060f648f4da94f4e1394068186e2709e4a5f4"

- name: neovim - remove previous build
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}/install/neovim"
    cmd: |
      make distclean

- name: neovim - configure
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}/install/neovim"
    cmd: |
      make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/bin/nvim"

- name: neovim - install
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}/install/neovim"
    cmd: |
      make -j install

- name: neovim - install packages
  ansible.builtin.command:
    cmd: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
