- name: kitty - Create download directory
  file:
   path: "{{ lookup('env', 'HOME') }}/install/kitty"
   state: directory

- name: kitty - Create installation directory
  file:
   path: "{{ lookup('env', 'HOME') }}/bin/kitty"
   state: directory

- name: kitty - Install kitty
  become: true
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/install/kitty"
    cmd: |
      GH_TOKEN="{{ env_vars['GH_TOKEN'] }}" gh release download --repo kovidgoyal/kitty v{{ kitty_release }} --pattern 'kitty-{{ kitty_release }}-x86_64.txz'
      tar Jxvf *.txz --directory={{ lookup('env', 'HOME') }}/bin/kitty
  when:
    - ansible_os_family == 'Debian'
