- name: clangd - Install
  become: true
  apt:
    name:
      - clangd-12
  when:
    - ansible_fact['distribution'] == 'Ubuntu'
  tags:
    - core
    - clangd
    - ubuntu

- name: clangd - Create alias
  shell: sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-12 100
  when:
    - ansible_fact['distribution'] == 'Ubuntu'
  tags:
    - core
    - clangd
    - ubuntu
