- name: go - Create installation directory
  ansible.builtin.command:
    cmd: "mkdir -p {{ lookup('env', 'HOME') }}/install/go"
  tags:
    - core
    - go

- name: go - Download go (linux)
  ansible.builtin.shell:
    chdir: "{{ lookup('env', 'HOME') }}/install/go"
    cmd: "curl -OL https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
  tags:
    - core
    - go

- name: go - Install go (linux)
  become: true
  ansible.builtin.shell:
    chdir: "{{ lookup('env', 'HOME') }}/install/go"
    cmd: rm -rf /usr/local/go && tar -C /usr/local -xzf "go{{ go_version }}.linux-amd64.tar.gz"
  tags:
    - core
    - go

- name: go - Install gopls
  ansible.builtin.command:
    cmd: >
      go install golang.org/x/tools/gopls@latest
  tags:
    - core
    - go

- name: go - Install delve
  ansible.builtin.command:
    cmd: >
      go install github.com/go-delve/delve/cmd/dlv@latest
  tags:
    - core
    - go

# - name: go - Install golangci-lint
#   ansible.builtin.command:
#     cmd: |
#       "go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{ golangci_lint_version }}"
#   tags:
#     - core
#     - go
