- name: Install app - neovim
  import_tasks: apps/neovim-build.yml
  tags:
    - neovim-build

- name: Install app - mcfly
  import_tasks: apps/mcfly.yml
  tags:
    - mcfly

- name: Install app - kitty
  import_tasks: apps/kitty.yml
  tags:
    - kitty
