- name: dotfiles - Install stow config
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/dotfiles"
    cmd: "stow stow"
  tags:
    - dotfiles

- name: dotfiles - Install cross-platform dotfiles
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/dotfiles/home"
    cmd: "stow {{ item }}"
  loop:
    - alacritty
#   - bat
#   - fzf
#   - git
#   - kitty
#   - latexmk
    - nvim
#   - pandoc
#   - scripts
#   - starship
#   - tmux
#   - vim
#   - zathura
#   - zsh
  tags:
    - dotfiles

- name: dotfiles - Install linux dotfiles
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/dotfiles/home_ubuntu"
    cmd: "stow {{ item }}"
  loop:
#   - code
    - i3
#   - zsh
  when:
    - ansible_os_family != 'Debian'
  tags:
    - dotfiles

- name: dotfiles - Install macos dotfiles
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/dotfiles/home_macos"
    cmd: "stow {{ item }}"
  loop:
    - zsh
  when:
    - ansible_os_family == 'Darwin'
  tags:
    - dotfiles
