- name: go - create installation directory
  file:
   path: "{{ lookup('env', 'HOME') }}/install/go"
   state: directory

- name: go - download go (linux)
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/install/go"

- name: go - uninstall previous version of go
  become: true
  file:
    path: "/usr/local/go"
    state: absent

- name: go - install go (linux)
  ansible.builtin.shell:
    chdir: "{{ lookup('env', 'HOME') }}/install/go"
    cmd: tar -C /usr/local -xzf "go{{ go_version }}.linux-amd64.tar.gz"

- name: go - install gopls
  ansible.builtin.command:
    cmd: >
      go install golang.org/x/tools/gopls@latest

- name: go - install delve
  ansible.builtin.command:
    cmd: >
      go install github.com/go-delve/delve/cmd/dlv@latest

- name: go - install golangci-lint
  ansible.builtin.command:
    cmd: |
      go install github.com/golangci/golangci-lint/cmd/golangci-lint@v{{ golangci_lint_version }}
  tags:
    - golangci
