---
- hosts: localhost
  vars_files:
    - vars.yml
    - .env_vars.yml
  environment: env_vars

  pre_tasks:
    - name: Print distribution
      ansible.builtin.debug:
        msg: "os family: {{ ansible_os_family }} - distribution: {{ ansible_facts['distribution'] }}"
      tags:
        - core

    - name: Github token
      ansible.builtin.debug:
        msg: "GH_TOKEN = {{ lookup('env', 'GH_TOKEN') }}"
      tags:
        - debug

    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - core
      when:
        - ansible_os_family == 'Debian'

  tasks:
    - name: Detect WSL
      become: true
      shell: grep -qi microsoft /proc/version && echo wsl || /bin/true
      register: detect_wsl_result
      tags:
        - full

# - name: Setup git
#   import_tasks: tasks/git-setup.yml
#   tags:
#     - full

    - name: apt - Install core packages - Debian-based
      import_tasks: tasks/apt/core.yml
      when:
        - ansible_os_family == 'Debian'
      tags:
        - core
        - full

    - name: Install i3
      import_tasks: tasks/apt/wm.yml
      when:
        - ansible_os_family == 'Debian'
      tags:
        - wm

# - name: Install core packages - Mac
#   tags:
#     - mac

    - name: Setup dotfiles
      import_tasks: "tasks/dotfiles.yml"
      tags:
        - dotfiles
        - full

    - name: Install snap packages
      import_tasks: tasks/snap-packages.yml
      tags:
        - full

    - name: Install pip and python packages
      import_tasks: tasks/pip-packages.yml
      tags:
        - full

    - name: Install go and go packages
      import_tasks: tasks/go-packages.yml
      tags:
        - full

    - name: Install cargo and rust packages
      import_tasks: tasks/cargo-packages.yml
      vars:
        is_wsl: '{{ detect_wsl_result.stdout == "wsl" }}'
      tags:
        - full

    - name: Install nvm and npm packages
      import_tasks: tasks/nvm-setup.yml
      tags:
        - full

    - name: Install apps
      import_tasks: tasks/apps.yml
      tags:
        - full
