- name: nvm - Remove previous nvm installation
  file:
    state: absent
    path: ".nvm"
  tags:
    - nvm

- name: nvm - Install
  shell:
    cmd: |
      export NVM_DIR="$HOME/.nvm" && (
        git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
        cd "$NVM_DIR"
        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
      ) && \. "$NVM_DIR/nvm.sh"
  tags:
    - nvm

- name: nvm - Install npm lts
  shell:
    cmd: |
      /usr/bin/env zsh -c "source ~/.zshrc && nvm install --lts"
  tags:
    - nvm

- name: nvm - Get npm version
  shell:
    cmd: |
      /usr/bin/env zsh -c "source ~/.zshrc && nvm current"
  register: nvm_version
  tags:
    - nvm

- name: nvm - Symlink npm
  become: true
  file:
    src: "{{ lookup('env', 'HOME') }}/.nvm/versions/node/{{ nvm_version.stdout }}/bin/npm"
    dest: /usr/bin/npm
    force: true
    state: link
  tags:
    - nvm

- name: nvm - Symlink node
  become: true
  file:
    src: "{{ lookup('env', 'HOME') }}/.nvm/versions/node/{{ nvm_version.stdout }}/bin/node"
    dest: /usr/bin/node
    force: true
    state: link
  tags:
    - nvm

- name: nvm - Install language servers
  community.general.npm:
    path: "{{ lookup('env', 'HOME') }}/.local/share/global-node-env/"
  tags:
    - nvm
